package io.rektplorer64.pickerkt.ui.ui.theme
import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF00639d)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFcde5ff)
val md_theme_light_onPrimaryContainer = Color(0xFF001d34)
val md_theme_light_secondary = Color(0xFF006d42)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFF82FFC8)
val md_theme_light_onSecondaryContainer = Color(0xFF002110)
val md_theme_light_tertiary = Color(0xFF755b00)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFffe084)
val md_theme_light_onTertiaryContainer = Color(0xFF241a00)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfbfdfd)
val md_theme_light_onBackground = Color(0xFF191c1d)
val md_theme_light_surface = Color(0xFFfbfdfd)
val md_theme_light_onSurface = Color(0xFF191c1d)
val md_theme_light_surfaceVariant = Color(0xFFdee3eb)
val md_theme_light_onSurfaceVariant = Color(0xFF42474d)
val md_theme_light_outline = Color(0xFF72777f)
val md_theme_light_inverseOnSurface = Color(0xFFeff1f1)
val md_theme_light_inverseSurface = Color(0xFF2d3132)

val md_theme_dark_primary = Color(0xFF95ccff)
val md_theme_dark_onPrimary = Color(0xFF003355)
val md_theme_dark_primaryContainer = Color(0xFF004a78)
val md_theme_dark_onPrimaryContainer = Color(0xFFcde5ff)
val md_theme_dark_secondary = Color(0xFF00e38f)
val md_theme_dark_onSecondary = Color(0xFF003920)
val md_theme_dark_secondaryContainer = Color(0xFF005230)
val md_theme_dark_onSecondaryContainer = Color(0xFF46ffae)
val md_theme_dark_tertiary = Color(0xFFf2c100)
val md_theme_dark_onTertiary = Color(0xFF3d2e00)
val md_theme_dark_tertiaryContainer = Color(0xFF584400)
val md_theme_dark_onTertiaryContainer = Color(0xFFffe084)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF191c1d)
val md_theme_dark_onBackground = Color(0xFFe0e3e3)
val md_theme_dark_surface = Color(0xFF191c1d)
val md_theme_dark_onSurface = Color(0xFFe0e3e3)
val md_theme_dark_surfaceVariant = Color(0xFF42474d)
val md_theme_dark_onSurfaceVariant = Color(0xFFc2c7ce)
val md_theme_dark_outline = Color(0xFF8c9198)
val md_theme_dark_inverseOnSurface = Color(0xFF191c1d)
val md_theme_dark_inverseSurface = Color(0xFFe0e3e3)

val seed = Color(0xFF8ac6ff)
val error = Color(0xFFba1b1b)